// Central registry of lazy route chunks. App.tsx loads only the chunk needed
// for the current route so the homepage does not spend bandwidth and CPU on
// pages the visitor may never open.

export const routeImports = {
  LegacyHome: () => import('./LegacyHome'),
  ThreePLPage: () => import('./agency/ThreePLPage'),
  PickupPage: () => import('./agency/PickupPage'),
  BookRedirect: () => import('./agency/BookRedirect'),
  StockoutsPage: () => import('./agency/StockoutsPage'),
  FishbowlPage: () => import('./agency/FishbowlPage'),
  CompetitorAlternativePages: () => import('./agency/CompetitorAlternativePages'),
  MeetingConfirmedPage: () => import('./agency/MeetingConfirmedPage'),
  ProspectReportRoute: () => import('./reports/StockSignalsReport'),
  FeaturesOverviewPage: () => import('./pages/features/FeaturesOverviewPage'),
  InventoryPage: () => import('./pages/features/InventoryPage'),
  PurchasingPage: () => import('./pages/features/PurchasingPage'),
  SalesPage: () => import('./pages/features/SalesPage'),
  ManufacturingPage: () => import('./pages/features/ManufacturingPage'),
  WarehousingPage: () => import('./pages/features/WarehousingPage'),
  ToolsServicesPage: () => import('./pages/features/ToolsServicesPage'),
  AccountingPage: () => import('./pages/features/AccountingPage'),
  ShopifyInventoryPage: () => import('./pages/ShopifyInventoryPage'),
  PricingPage: () => import('./pages/PricingPage'),
  AboutPage: () => import('./pages/AboutPage'),
  BlogPage: () => import('./pages/BlogPage'),
  InventoryManagementGuidePage: () => import('./pages/InventoryManagementGuidePage'),
  PartnersPage: () => import('./pages/PartnersPage'),
  PrivacyPolicyPage: () => import('./pages/PrivacyPolicyPage'),
  TermsOfServicePage: () => import('./pages/TermsOfServicePage'),
  AppPrivacyPage: () => import('./pages/AppPrivacyPage'),
  DataSafetyPage: () => import('./pages/DataSafetyPage'),
  EulaPage: () => import('./pages/EulaPage'),
  SupportPage: () => import('./pages/SupportPage'),
  DeleteAccountPage: () => import('./pages/DeleteAccountPage'),
  ContactPage: () => import('./pages/ContactPage'),
  SitemapPage: () => import('./pages/SitemapPage'),
  SmsProgramPage: () => import('./pages/SmsProgramPage'),
  NotFoundPage: () => import('./pages/NotFoundPage'),
};
